title: Harsh Vardhan, Ph.D.
description: Research Scientist â€” Vanderbilt University, Institute for Software Integrated Systems
url: "https://vardhah.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty

defaults:
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: work

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
